'use client';
import {useEffect,useRef,useState,useCallback} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine,LineChart,Line} from 'recharts';
import {ChartNoAxesColumnIncreasing,Download,Play,Upload,RefreshCw,FileText,Code2,SlidersHorizontal,Copy,LoaderCircle,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {analyse,SAMPLE_CONFIG,MARKETS,DEFAULT_FEES,formatPct,compactReport,markdownReport,validateConfig,localParts} from '@/lib/research/engine.mjs';
import {parseCSV,dataCSV} from '@/lib/research/data.mjs';

const COLORS=['#315ee8','#159589','#9c6cca','#db903e','#cf5974','#64748b'];
const share=(x:number|null)=>x===null?'—':`${(x*100).toFixed(1)}%`;
const pvalue=(x:number|null)=>x===null||x===undefined?'—':x<.001?'<0.001':x.toFixed(3);
const sign=(x:number)=>x<0?'negative':x>0?'positive':'';
const names:Record<string,string>={'D05.SI':'DBS','O39.SI':'OCBC','U11.SI':'UOB','^STI':'STI index'};
function download(name:string,body:any,type='text/plain'){const blob=body instanceof Blob?body:new Blob([body],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Choice({value,onChange,items,label}:{value:string,onChange:(s:string)=>void,items:[string,string][],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>;}
function Panel({title,sub,children,foot,extra}:{title:string,sub?:string,children:React.ReactNode,foot?:string,extra?:React.ReactNode}){return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2>{sub&&<p className="panel-sub">{sub}</p>}</div>{extra}</div>{children}{foot&&<p className="panel-foot">{foot}</p>}</section>;}
function DataTable({headers,rows}:{headers:string[],rows:React.ReactNode[][]}){return <Table className="study-table"><TableHeader><TableRow>{headers.map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((x,j)=><TableCell key={j}>{x}</TableCell>)}</TableRow>)}</TableBody></Table>;}
function Metric({label,value,detail,color}:{label:string,value:string,detail:string,color?:string}){return <div className="metric"><div className="metric-label">{label}</div><div className={`metric-value ${color||''}`}>{value}</div><div className="metric-detail">{detail}</div></div>;}
export default function Home(){
 const [config,setConfig]=useState<any>(structuredClone(SAMPLE_CONFIG)),[fees,setFees]=useState<any>({...SAMPLE_CONFIG.fees}),[data,setData]=useState<any>(null),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('overview'),[period,setPeriod]=useState('Year'),[focus,setFocus]=useState('D05.SI'),[copied,setCopied]=useState(false),[exporting,setExporting]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),active=useRef<any>(null),running=useRef(false);
 const accept=useCallback((dataset:any,c:any)=>{const r=analyse(dataset,c);setData(dataset);setResult(r);setConfig(r.config);setFees(r.config.fees);setFocus(r.config.tickers[0]);active.current=r;return r;},[]);
 const loadSample=useCallback(async()=>{setBusy(true);setError('');setNotice('');try{const resp=await fetch('/data/sg-banks.json');if(!resp.ok)throw Error('Saved study is unavailable. You can still download prices or import CSV.');accept(await resp.json(),structuredClone(SAMPLE_CONFIG));}catch(e){setError(e instanceof Error?e.message:'Unable to load study.');}finally{setBusy(false);}},[accept]);
 useEffect(()=>{void loadSample();},[loadSample]);
 const run=useCallback(async(c:any)=>{if(running.current)throw Error('A study is already running.');running.current=true;setBusy(true);setError('');setNotice('');try{const cfg=validateConfig(c);const response=await fetch('/api/prices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});const dataset:any=await response.json();if(!response.ok)throw Error(dataset.error||'Price download failed.');const r=accept(dataset,cfg);setNotice('Study complete. Results use the latest available completed sessions in your selected range.');return compactReport(r);}catch(e){setError(e instanceof Error?e.message:'Study failed.');throw e;}finally{running.current=false;setBusy(false);}},[accept]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();for(const tool of [{name:'run_stock_study',title:'Run stock study',description:'Download hourly prices, run the research calculation and update the visible study. Returns the compact report.',inputSchema:{type:'object',properties:{market:{enum:['SGX','US']},tickers:{type:'array',items:{type:'string'},minItems:1,maxItems:5},start:{type:'string'},end:{type:'string'}},required:['market','tickers','start','end'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>run({...SAMPLE_CONFIG,...input,benchmark:'',eventDate:'',fees:{...DEFAULT_FEES}})},{name:'get_stock_study',title:'Read current stock study',description:'Read the currently displayed study and its settings without fetching new prices.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>active.current?compactReport(active.current):{error:'No study is loaded.'}}]){try{Promise.resolve(context.registerTool(tool,{signal:abort.signal})).catch(()=>{});}catch{}}return ()=>abort.abort();},[run]);
 function edit(key:string,value:any){setConfig((c:any)=>({...c,[key]:value}));}
 async function importFile(file:File){setError('');setBusy(true);setNotice('');try{if(file.size>25*1024*1024)throw Error('CSV must be under 25 MB.');const dataset=parseCSV(await file.text());const symbols=[...new Set(dataset.bars.map((b:any)=>b.ticker))];if(symbols.length>5)throw Error('Import at most 5 tickers at a time.');const dates=dataset.bars.map((b:any)=>b.date||localParts(b.timestamp,(MARKETS as any)[config.market].zone).date).sort();accept(dataset,{...config,tickers:symbols,benchmark:'',start:dates[0],end:dates.at(-1),fees});setNotice(`Imported ${file.name}. Tickers and dates came from the file; ${config.market} session rules were used.`);}catch(e){setError(e instanceof Error?e.message:'CSV import failed.');}finally{setBusy(false);if(fileInput.current)fileInput.current.value='';}}
 async function exportExcel(){if(!result||!data)return;setExporting(true);setError('');try{const {makeWorkbook}=await import('@/lib/research/workbook.mjs');download(`Stock_Time_Lab_${result.config.tickers[0]}.xlsx`,makeWorkbook(result,data),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}catch(e){setError(e instanceof Error?e.message:'Export failed.');}finally{setExporting(false);}}
 const r=result,s=r?.summaries[0],m=r?.market,selected=r?.summaries.find((x:any)=>x.ticker===focus)||s;
 const hourData=r?.market.slots.map((slot:string,i:number)=>{const row:any={interval:slot};r.tickers.forEach((t:string)=>{row[t]=r.hourly.find((x:any)=>x.ticker===t&&x.slot===i)?.mean*100;});return row;})||[];
 const dirty=r&&JSON.stringify({...config,fees:r.config.fees})!==JSON.stringify(r.config);
 const money=(x:number)=>new Intl.NumberFormat('en-SG',{style:'currency',currency:m?.currency||'SGD',maximumFractionDigits:2}).format(x);
 return <><header className="app-header"><div className="brand"><span className="brand-mark"><ChartNoAxesColumnIncreasing size={23}/></span>Stock Time Lab</div><div className="header-links"><span className="private-label">Research workspace</span><a href="https://github.com/ffelixq/Stock-Time-Lab" target="_blank" rel="noreferrer" className="actions"><Code2 size={17}/><span className="github-text">Source code</span></a></div></header>
 <main className="workspace"><div className="page-title"><div><div className="eyebrow">Intraday research</div><h1>Find the pattern. Test the evidence.</h1><p className="description">Compare trading hours, check consistency and account for costs.</p></div><div className="actions"><button className="button" disabled={!r||busy} onClick={()=>{setTab('report');document.getElementById('study-tabs')?.scrollIntoView({behavior:'smooth',block:'start'});}}><FileText/>Research report</button><button className="button primary" disabled={!r||exporting||busy} onClick={exportExcel}>{exporting?<LoaderCircle className="spin"/>:<Download/>}Export Excel</button></div></div>
 <div className="layout"><aside className="settings"><div className="settings-heading"><h3 className="actions"><SlidersHorizontal size={16}/>Study settings</h3></div><form onSubmit={e=>{e.preventDefault();void run({...config,fees}).catch(()=>{});}}><div className="field"><span>Market</span><Choice value={config.market} label="Market" onChange={value=>{setConfig((c:any)=>({...c,market:value,tickers:value==='SGX'?['D05.SI','O39.SI','U11.SI']:['NVDA','AMD'],benchmark:value==='US'?'SPY':'',eventDate:'',eventName:''}));setFees({...DEFAULT_FEES});}} items={Object.entries(MARKETS).map(([k,v])=>[k,v.name])}/></div>
 <label className="field"><span>Primary stock</span><input aria-label="Primary stock" value={config.tickers[0]||''} onChange={e=>edit('tickers',[e.target.value.toUpperCase(),...config.tickers.slice(1)])} placeholder="D05.SI" required/><small>{config.market==='SGX'?'Yahoo symbols, e.g. D05.SI for DBS':'Yahoo symbols, e.g. NVDA, AAPL'}</small></label>
 <label className="field"><span>Peer stocks</span><input aria-label="Peer stocks" value={config.tickers.slice(1).join(', ')} onChange={e=>edit('tickers',[config.tickers[0],...e.target.value.toUpperCase().split(',').map(x=>x.trim())])} placeholder="O39.SI, U11.SI"/><small>Up to four peers, separated by commas</small></label>
 <label className="field"><span>Benchmark <span className="muted">(optional)</span></span><input aria-label="Benchmark" value={config.benchmark} onChange={e=>edit('benchmark',e.target.value.toUpperCase())} placeholder={config.market==='SGX'?'^STI':'SPY'}/></label>
 <label className="field"><span>Start date</span><input type="date" aria-label="Start date" value={config.start} onChange={e=>edit('start',e.target.value)} required/></label><label className="field"><span>End date</span><input type="date" aria-label="End date" value={config.end} onChange={e=>edit('end',e.target.value)} required/></label>
 <div className="run-block"><button type="button" className="button small ghost" onClick={()=>{const end=new Date(),start=new Date();start.setUTCFullYear(start.getUTCFullYear()-1);setConfig((c:any)=>({...c,start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}));}}>Use latest year</button><button className="button primary" type="submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Play/>}{busy?'Analysing…':'Download & run study'}</button><p className="settings-note">Hourly prices. Completed sessions only. No AI tokens or API key required.</p></div>
 <details><summary>Events & exclusions</summary><label className="field"><span>Event date</span><input type="date" value={config.eventDate} onChange={e=>edit('eventDate',e.target.value)}/><small>Use the first affected local trading date.</small></label><label className="field"><span>Event name</span><input value={config.eventName} onChange={e=>edit('eventName',e.target.value)}/></label><label className="field"><span>Exclude dates</span><textarea rows={2} value={config.excludeDates.join(', ')} placeholder="2025-04-03, 2025-04-04" onChange={e=>edit('excludeDates',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label className="field"><span>Later-period share (%)</span><input type="number" min="10" max="40" value={config.holdoutPercent} onChange={e=>edit('holdoutPercent',Number(e.target.value))}/></label><button className="button small" type="button" disabled={!data||busy} onClick={()=>{try{accept(data,{...config,fees});setNotice('Recalculated using the loaded prices.');setError('');}catch(e){setError(e instanceof Error?e.message:'Recalculation failed.');}}}>Recalculate loaded data</button></details></form>
 <div className="settings-bottom"><button className="button small" disabled={busy} onClick={()=>fileInput.current?.click()}><Upload/>Import CSV</button><button className="button small" disabled={busy} onClick={loadSample}><RefreshCw/>Load DBS study</button><input ref={fileInput} className="file-input" aria-label="Import CSV file" type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);}}/></div></aside>
 <div className="results" aria-busy={busy}>{error&&<div className="error" role="alert">{error}</div>}{notice&&<p className="status-text" role="status">{notice}</p>}{dirty&&<div className="notice">Settings have changed. Run the study to update the results below.</div>}{!r?<div className="panel loading" role="status">{busy?'Loading the saved DBS study…':'Choose your stocks or import hourly prices to begin.'}</div>:<>
 <div className="source-bar"><div className="actions"><span className="source-chip">{r.source.startsWith('Saved')?'SAVED STUDY':r.source.startsWith('Imported')?'IMPORTED DATA':'DOWNLOADED PRICES'}</span><span>{r.start} — {r.end}</span></div><span>{r.n} matching sessions · {m.zone}</span></div>
 <div className="metrics"><Metric label={`${names[s.ticker]||s.ticker} · ${m.aLabel}`} value={formatPct(s.a.mean)} detail={`${m.aTime} · mean return`} color={sign(s.a.mean)}/><Metric label={`${names[s.ticker]||s.ticker} · ${m.bLabel}`} value={formatPct(s.b.mean)} detail={`${m.bTime} · mean return`} color={sign(s.b.mean)}/><Metric label="First up, second down" value={share(s.both)} detail={`${s.bothCount} of ${r.n} sessions`}/><Metric label="First-session net P/L" value={money(r.costs.net)} detail={`Average on ${money(r.costs.notional)}`} color={sign(r.costs.net)}/></div>
 <Tabs value={tab} onValueChange={setTab} className="study-tabs" id="study-tabs"><TabsList variant="line" aria-label="Research views">{[['overview','Overview'],['hours','Hours & periods'],['checks','Evidence checks'],['costs','Trading costs'],['report','Report & data']].map(([v,t])=><TabsTrigger key={v} value={v}>{t}</TabsTrigger>)}</TabsList>
 <TabsContent value="overview"><Panel title="The shape of the trading day" sub="Average return within each interval, across matching complete sessions" extra={<div className="chart-legend">{r.tickers.map((t:string,i:number)=><span key={t}><i className="legend-swatch" style={{background:COLORS[i]}}/>{names[t]||t}</span>)}</div>} foot={`${m.zone} · ${m.break?'The noon–1 pm trading break and reopening gap are separate.':'The final interval, 15:30–16:00, is 30 minutes.'} A positive average does not mean a gain on most days.`}><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={hourData} margin={{left:4,right:16,top:18,bottom:0}} barGap={3}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="interval" axisLine={false} tickLine={false} tick={{fill:'#6c7890',fontSize:12}} dy={8}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#6c7890',fontSize:12}} tickFormatter={v=>`${v.toFixed(2)}%`} width={70}/><Tooltip formatter={(v:any)=>`${Number(v).toFixed(3)}%`} contentStyle={{borderRadius:8,border:'1px solid #dce4ee',fontSize:13}}/><ReferenceLine y={0} stroke="#a7b4c9"/>{r.tickers.map((t:string,i:number)=><Bar key={t} dataKey={t} name={names[t]||t} fill={COLORS[i]} radius={[3,3,0,0]} maxBarSize={26}/>)}</BarChart></ResponsiveContainer></div></Panel>
 <div className="insight"><strong>What the numbers say</strong>{r.findings[0]} {r.findings[2]}</div>
 <Panel title="Same days. Different stocks." sub="Peer comparisons use the same sample and session definitions."><DataTable headers={['Instrument',m.aLabel,m.bLabel,'First up','Second down','Both pattern']} rows={r.summaries.map((x:any,i:number)=>[<span key="name" style={{color:COLORS[i]}}>{names[x.ticker]||x.ticker}<span className="subtext">{x.ticker}{x.ticker===r.config.benchmark?' · benchmark':''}</span></span>,formatPct(x.a.mean),formatPct(x.b.mean),share(x.a.up),share(x.b.down),share(x.both)])}/></Panel>
 <Panel title="Consistency over time" sub={`${names[focus]||focus} · trailing 60-session average`} extra={<Choice value={focus} onChange={setFocus} label="Chart instrument" items={r.tickers.map((t:string)=>[t,names[t]||t])}/>} foot="Each point uses the 60 sessions ending on that date. Overlapping windows are descriptive, not independent tests."><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><LineChart data={r.rolling.filter((x:any)=>x.ticker===focus&&x.a60!==null)} margin={{left:4,right:18,top:15,bottom:0}}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" minTickGap={65} tickFormatter={v=>v.slice(0,7)} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#6c7890'}}/><YAxis tickFormatter={v=>`${(v*100).toFixed(2)}%`} width={70} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#6c7890'}}/><Tooltip formatter={(v:any)=>formatPct(Number(v))}/><ReferenceLine y={0} stroke="#a7b4c9"/><Line type="monotone" dataKey="a60" name={m.aLabel} stroke="#315ee8" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="b60" name={m.bLabel} stroke="#159589" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><div className="panel-foot"><span style={{color:'#315ee8'}}>━ {m.aLabel}</span>　<span style={{color:'#159589'}}>━ {m.bLabel}</span></div></Panel></TabsContent>
 <TabsContent value="hours"><Panel title="Hourly statistics" sub="Means, uncertainty and corrected statistical tests" extra={<Choice value={focus} onChange={setFocus} label="Statistics instrument" items={r.tickers.map((t:string)=>[t,names[t]||t])}/>} foot="95% interval: Newey–West, 5 lags. Holm p adjusts for every selected stock/hour combination. A dash means insufficient data or zero variance."><DataTable headers={['Interval','Mean','Median','Up days','95% interval','Holm p','N']} rows={r.hourly.filter((x:any)=>x.ticker===focus).map((x:any)=>[x.interval,formatPct(x.mean),formatPct(x.median),share(x.up),`${formatPct(x.low)} to ${formatPct(x.high)}`,pvalue(x.adjustedP),x.n])}/></Panel>
 <Panel title="Period comparison" sub={`${names[focus]||focus} · average session returns, not annual investment returns`}><div className="small-controls"><Choice value={period} onChange={setPeriod} label="Period grouping" items={['Year','Month','Weekday','Recent'].map(x=>[x,x])}/></div><DataTable headers={['Period',m.aLabel,m.bLabel,'First median','Second median','N']} rows={r.periods.filter((x:any)=>x.ticker===focus&&x.group===period&&x.metric==='a').map((x:any)=>{const b=r.periods.find((y:any)=>y.ticker===focus&&y.group===period&&y.label===x.label&&y.metric==='b');return [x.label,formatPct(x.mean),formatPct(b.mean),formatPct(x.median),formatPct(b.median),x.n];})}/></Panel>
 <Panel title="What follows the first session?" sub={`${names[focus]||focus} · second-session returns conditional on the earlier move`} foot="Subgroups are exploratory. Full-sample thresholds describe this dataset and are not a tradable signal."><DataTable headers={['Earlier condition','Mean later return','Down share','N']} rows={r.conditional.filter((x:any)=>x.ticker===focus).map((x:any)=>[<span key="c" style={{whiteSpace:'normal',display:'block',maxWidth:340}}>{x.label}</span>,formatPct(x.mean),share(x.down),x.n])}/></Panel></TabsContent>
 <TabsContent value="checks"><div className="small-controls"><span>Instrument</span><Choice value={focus} onChange={setFocus} label="Evidence instrument" items={r.tickers.map((t:string)=>[t,names[t]||t])}/></div><Panel title="Does the result depend on extreme days?" sub={`${names[focus]||focus} · ${m.aLabel.toLowerCase()}`} foot="Removing extreme observations is a sensitivity check. Trimmed statistics are descriptive; their confidence intervals are intentionally omitted."><DataTable headers={['Sample','Mean','Median','95% interval','N']} rows={r.robustness.filter((x:any)=>x.ticker===focus&&x.metric==='a').map((x:any)=>[x.test,formatPct(x.mean),formatPct(x.median),x.low===null?'—':`${formatPct(x.low)} to ${formatPct(x.high)}`,x.n])}/></Panel>
 <Panel title="Earlier versus later sessions" sub="A chronological stability check" foot="Both periods are visible in this report. Once reviewed, the later period is no longer an untouched holdout. Use future unseen data for confirmation."><DataTable headers={['Session','Earlier mean','Earlier N','Later mean','Later N']} rows={r.stability.filter((x:any)=>x.ticker===focus).map((x:any)=>[x.metric==='a'?m.aLabel:m.bLabel,formatPct(x.early.mean),x.early.n,formatPct(x.late.mean),x.late.n])}/></Panel>
 {r.comparisons.length>0&&<Panel title="Return above peers" sub={`${r.config.tickers[0]} minus comparator, paired by date`} foot="Excess returns are percentage-point differences. Correlation measures co-movement, not causation."><DataTable headers={['Comparator','Session','Mean excess','Correlation','Holm p']} rows={r.comparisons.map((x:any)=>[x.other,x.metric==='a'?m.aLabel:m.bLabel,formatPct(x.mean),x.correlation===null?'—':x.correlation.toFixed(2),pvalue(x.adjustedP)])}/></Panel>}
 {r.events.length>0?<Panel title={r.config.eventName||'Event comparison'} sub={`First affected local session: ${r.config.eventDate}`} foot="Before/after differences are associations. Approximate difference intervals combine the two periods’ HAC variances and assume independent period means; they do not identify a causal effect."><DataTable headers={['Window','Session','Before mean','After mean','Difference','Holm p','N pre / post']} rows={r.events.filter((x:any)=>x.ticker===focus).map((x:any)=>[x.label,x.metric==='a'?m.aLabel:m.bLabel,formatPct(x.before.mean),formatPct(x.after.mean),formatPct(x.difference),pvalue(x.adjustedP),`${x.before.n} / ${x.after.n}`])}/></Panel>:<div className="insight">Add an event date under “Events & exclusions” to compare before and after periods.</div>}
 <Panel title="Data quality" sub="Rows and sessions retained before the common-date comparison"><DataTable headers={['Instrument','Source bars','Invalid bars','Off-session bars','Incomplete days','Complete days','Matched days']} rows={r.diagnostics.map((x:any)=>[x.ticker,x.inputBars,x.invalidBars,x.outsideSession,x.incompleteDays,x.completeDays,x.matchedDays])}/></Panel></TabsContent>
 <TabsContent value="costs"><Panel title="What remains after costs?" sub={`${r.config.tickers[0]} · buy at the first-session open, sell at its end`} foot="Illustrative fractional position with fixed cash per trade. Fees use each day’s exit value; spread/slippage applies on both sides. No compounding, board-lot rounding, short selling or FX conversion."><div className="fees-grid">{[['notional',`Trade size (${m.currency})`],['brokerPercent','Broker commission (%) / side'],['brokerMinimum',`Minimum commission (${m.currency}) / side`],['exchangePercent','Exchange fees (%) / side'],['settlement',`Fixed fee (${m.currency}) / side`],['taxPercent','Tax on fees (%)'],['slippageBps','Spread + slippage (bps) / side']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input type="number" step="any" min="0" value={fees[key]} onChange={e=>setFees((f:any)=>({...f,[key]:Number(e.target.value)}))}/></label>)}</div><div className="small-controls"><button className="button primary" onClick={()=>{try{const rr=analyse(data,{...r.config,fees});setResult(rr);active.current=rr;setConfig((c:any)=>({...c,fees}));setError('');setNotice('Cost estimates updated. Exports include these assumptions.');}catch(e){setError(e instanceof Error?e.message:'Invalid fee inputs.');}}}>Apply costs</button><span className="muted">1 basis point = 0.01%</span></div><div className="cost-summary">{[['Gross return',r.costs.gross],['Fees + tax',-r.costs.fees],['Execution costs',-r.costs.execution],['Net return',r.costs.net]].map(([label,val])=><div key={label as string}><div className="metric-label">{label}</div><div className={`metric-value ${sign(val as number)}`}>{money(val as number)}</div></div>)}</div></Panel><div className="insight"><strong>Entered assumptions matter</strong>{share(r.costs.netWin)} of the first-session trades were positive after the displayed costs. Fees begin at zero for new markets. The saved DBS study uses its original illustrative exchange fees; verify your current broker’s rates.</div></TabsContent>
 <TabsContent value="report"><Panel title="Your research handoff" sub="Give the summary and JSON to ChatGPT for stock-specific follow-up analysis." extra={<div className="actions"><button className="button small" onClick={async()=>{try{await navigator.clipboard.writeText(markdownReport(r));setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError('Clipboard access is unavailable. Download the summary instead.');}}}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy summary'}</button><button className="button small" onClick={()=>download('study-summary.md',markdownReport(r),'text/markdown')}>Summary</button><button className="button small" onClick={()=>download('study-results.json',JSON.stringify(compactReport(r),null,2),'application/json')}>JSON</button><button className="button small" onClick={()=>download('source-prices.csv',dataCSV(data,r.config.market),'text/csv')}>Source CSV</button><button className="button small" onClick={()=>download('study-config.json',JSON.stringify(r.config,null,2),'application/json')}>Settings</button></div>}><div className="report-preview">{r.findings.join('\n\n')}</div></Panel>
 <Panel title="Method & provenance"><dl className="method-grid"><dt>Source</dt><dd>{r.source}</dd><dt>Retrieved</dt><dd>{r.retrievedAt?new Date(r.retrievedAt).toLocaleString('en-SG',{timeZone:'Asia/Singapore'})+' SGT':'Not supplied'}</dd><dt>Engine version</dt><dd>{r.version}</dd><dt>First session</dt><dd>{m.aTime}</dd><dt>Second session</dt><dd>{m.bTime}</dd><dt>Uncertainty</dt><dd>95% Newey–West intervals, 5 lags, large-sample normal approximation</dd></dl><ul className="notes-list">{r.warnings.map((x:string)=><li key={x}>{x}</li>)}</ul></Panel>
 <Panel title="CSV format & local script" sub="Import a broker/provider export, or run the same engine from your computer."><div style={{padding:'0 23px 23px',fontSize:14}}><p className="schema">ticker,date,time,open,high,low,close,volume</p><p className="muted" style={{marginTop:10}}>Use hourly bars labelled by their start time in the exchange timezone. Alternatively provide an ISO timestamp with a UTC offset. Optional dividend and split columns use 1/0 flags. Import stays in this browser and is not uploaded.</p><p className="schema" style={{marginTop:17}}>node scripts/analyse.mjs --config study-config.json --csv source-prices.csv --out outputs/my-study</p><p style={{marginTop:15}}><a className="source-link" href="https://github.com/ffelixq/Stock-Time-Lab#readme" target="_blank" rel="noreferrer">Setup instructions & source code</a></p></div></Panel></TabsContent></Tabs>
 <div className="footer"><span>Observed price patterns · not a forecast or trade execution system</span><span>Stock Time Lab / v{r.version}</span></div></>}</div></div></main></>;
}
