// Dependency-free OOXML export for the application and CLI. Formula cells include
// cached values for viewers and recalculate in Excel. Statistical tests are snapshots.
import {localParts,VERSION} from './engine.mjs';
const enc=new TextEncoder();
const xml=s=>String(s??'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
const F=(f,v,s=2)=>({f,v,s});const N=(v,s=2)=>({v,s});const D=s=>({v:Date.parse(s+'T00:00:00Z')/86400000+25569,s:4});
const crcTable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=(n&1)?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(bytes){let c=0xffffffff;for(const x of bytes)c=crcTable[(c^x)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function zip(entries){let offset=0;const chunks=[],central=[];const u16=(view,n,v)=>view.setUint16(n,v,true),u32=(view,n,v)=>view.setUint32(n,v,true);
 for(const [path,text] of Object.entries(entries)){const name=enc.encode(path),data=enc.encode(text),sum=crc(data),head=new Uint8Array(30+name.length),h=new DataView(head.buffer);u32(h,0,0x04034b50);u16(h,4,20);u16(h,6,0x800);u16(h,12,33);u32(h,14,sum);u32(h,18,data.length);u32(h,22,data.length);u16(h,26,name.length);head.set(name,30);chunks.push(head,data);const cd=new Uint8Array(46+name.length),v=new DataView(cd.buffer);u32(v,0,0x02014b50);u16(v,4,20);u16(v,6,20);u16(v,8,0x800);u16(v,14,33);u32(v,16,sum);u32(v,20,data.length);u32(v,24,data.length);u16(v,28,name.length);u32(v,42,offset);cd.set(name,46);central.push(cd);offset+=head.length+data.length;}
 const centralSize=central.reduce((s,b)=>s+b.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);u32(e,0,0x06054b50);u16(e,8,central.length);u16(e,10,central.length);u32(e,12,centralSize);u32(e,16,offset);const out=new Uint8Array(offset+centralSize+22);let pos=0;for(const bytes of [...chunks,...central,end]){out.set(bytes,pos);pos+=bytes.length;}return out;
}
function sheet(rows,widths=[],filter=true,headerRow=1){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${col(Math.max(...rows.map(r=>r.length))-1)}${rows.length}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="${headerRow}" topLeftCell="A${headerRow+1}" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="20"/><cols>${(widths.length?widths:[25,...Array(22).fill(18)]).map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${rows.map((r,i)=>`<row r="${i+1}"${i+1===headerRow?' ht="28" customHeight="1"':''}>${r.map((raw,j)=>{const item=typeof raw==='object'&&raw!==null?raw:{v:raw};const style=i+1===headerRow?1:(item.s||0),ref=col(j)+(i+1);if(item.v===null||item.v===undefined||typeof item.v==='number'&&!Number.isFinite(item.v))return `<c r="${ref}" s="${style}"/>`;if(item.f)return `<c r="${ref}" s="${style}"><f>${xml(item.f)}</f><v>${item.v}</v></c>`;if(typeof item.v==='number')return `<c r="${ref}" s="${style}"><v>${item.v}</v></c>`;return `<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xml(item.v)}</t></is></c>`;}).join('')}</row>`).join('')}</sheetData>${filter?`<autoFilter ref="A${headerRow}:${col(rows[headerRow-1].length-1)}${rows.length}"/>`:''}<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/></worksheet>`;}
export function makeWorkbook(r,dataset){
 const sheets=[],add=(name,rows,widths,filter=true,headerRow=1)=>sheets.push({name,xml:sheet(rows,widths,filter,headerRow)}),rawRows=[['Ticker','Local date','Local start time','Open','High','Low','Close','Volume']],rawMap=new Map();
 for(const raw of dataset.bars){const b=raw.date?raw:{...raw,...localParts(raw.timestamp,r.market.zone)};rawMap.set(`${b.ticker}|${b.date}|${b.time}`,rawRows.length+1);rawRows.push([b.ticker,D(b.date),b.time,N(b.open,3),N(b.high,3),N(b.low,3),N(b.close,3),b.volume]);}
 const dailyRows=[['Ticker','Date','Weekday','First open','First close','Second open','Second close','First return','Second return','Reopening gap','Day return','First up & second down',...r.market.slots.map((t,i)=>`${t}–${r.market.ends[i]}`),'Dividend date','Split date']];
 for(const d of r.daily){const row=dailyRows.length+1,refs=d.bars.map(b=>rawMap.get(`${b.ticker}|${b.date}|${b.time}`));dailyRows.push([d.ticker,D(d.date),d.weekday,F(`Raw!D${refs[0]}`,d.open,3),F(`Raw!G${refs[r.market.a-1]}`,d.aClose,3),F(`Raw!D${refs[r.market.a]}`,d.bOpen,3),F(`Raw!G${refs.at(-1)}`,d.close,3),F(`E${row}/D${row}-1`,d.a),F(`G${row}/F${row}-1`,d.b),F(`F${row}/E${row}-1`,d.gap),F(`G${row}/D${row}-1`,d.day),F(`IF(AND(H${row}>0,I${row}<0),1,0)`,d.a>0&&d.b<0?1:0,0),...d.hours.map((x,i)=>F(`Raw!G${refs[i]}/Raw!D${refs[i]}-1`,x)),d.dividend?1:0,d.split?1:0]);}
 const end=dailyRows.length,overview=[['Stock Time Lab',r.config.tickers[0]],['Period',`${r.start} to ${r.end}`],['Sessions',`${r.market.aLabel}: ${r.market.aTime}; ${r.market.bLabel}: ${r.market.bTime}; ${r.market.zone}`],['Instrument','First mean','Second mean','First up','Second down','Both pattern','N']];
 for(const s of r.summaries){const row=overview.length+1,q=`A${row}`;overview.push([s.ticker,F(`AVERAGEIF(Daily!$A$2:$A$${end},${q},Daily!$H$2:$H$${end})`,s.a.mean),F(`AVERAGEIF(Daily!$A$2:$A$${end},${q},Daily!$I$2:$I$${end})`,s.b.mean),N(s.a.up),N(s.b.down),F(`AVERAGEIF(Daily!$A$2:$A$${end},${q},Daily!$L$2:$L$${end})`,s.both),F(`COUNTIF(Daily!$A$2:$A$${end},${q})`,s.a.n,0)]);}
 overview.push([],['Analysis findings'],...r.findings.map(x=>[x]),[],['Calculation note','Raw → Daily → Overview use live formulas. Statistical outputs elsewhere are calculation snapshots; rerun the programme to update them.']);
 add('Overview',overview,[39,24,24,18,18,18,14],false,4);
 const statCols=['N','Mean','Median','SD','Up share','Down share','Flat share','95% low','95% high','HAC p','Holm p','5th percentile','95th percentile','5% trimmed mean'];
 const statRow=x=>[x.n,...['mean','median','sd','up','down','flat','low','high'].map(k=>N(x[k])),N(x.p,3),N(x.adjustedP,3),N(x.p05),N(x.p95),N(x.trimmed)];
 add('Hourly',[['Ticker','Interval','Minutes',...statCols],...r.hourly.map(x=>[x.ticker,x.interval,x.durationMinutes,...statRow(x)])]);
 add('Periods',[['Ticker','Group','Period','Session',...statCols],...r.periods.map(x=>[x.ticker,x.group,x.label,x.metric==='a'?r.market.aLabel:r.market.bLabel,...statRow(x)])]);
 add('Conditional',[['Ticker','Condition',...statCols],...r.conditional.map(x=>[x.ticker,x.label,...statRow(x)])],[19,64,...Array(14).fill(18)]);
 add('Robustness',[['Ticker','Session','Sensitivity check',...statCols],...r.robustness.map(x=>[x.ticker,x.metric==='a'?r.market.aLabel:r.market.bLabel,x.test,...statRow(x)])],[19,24,55,...Array(14).fill(18)]);
 add('Peers',[['Primary','Comparator','Session','Correlation',...statCols],...r.comparisons.map(x=>[x.ticker,x.other,x.metric==='a'?r.market.aLabel:r.market.bLabel,N(x.correlation,3),...statRow(x)])]);
 add('Events',[['Ticker','Event','Date','Window','Session','Before N','Before mean','After N','After mean','Difference','95% low','95% high','Raw p','Holm p'],...r.events.map(x=>[x.ticker,x.name,D(x.date),x.label,x.metric==='a'?r.market.aLabel:r.market.bLabel,x.before.n,N(x.before.mean),x.after.n,N(x.after.mean),N(x.difference),N(x.low),N(x.high),N(x.p,3),N(x.adjustedP,3)])]);
 add('Stability',[['Ticker','Session','Split date','Earlier N','Earlier mean','Later N','Later mean','Note'],...r.stability.map(x=>[x.ticker,x.metric==='a'?r.market.aLabel:r.market.bLabel,D(x.splitDate),x.early.n,N(x.early.mean),x.late.n,N(x.late.mean),x.note])]);
 const f=r.costs.assumptions,fees=[['Editable cost assumptions','Value'],['Trade size',N(f.notional,5)],['Broker commission % / side',N(f.brokerPercent,5)],['Minimum broker fee / side',N(f.brokerMinimum,5)],['Exchange fee % / side',N(f.exchangePercent,5)],['Fixed fee / side',N(f.settlement,5)],['Tax on fees %',N(f.taxPercent,5)],['Spread + slippage bps / side',N(f.slippageBps,5)],[],['Average gross',F(`AVERAGE(C14:C${13+r.costs.n})`,r.costs.gross,3)],['Average net',F(`AVERAGE(F14:F${13+r.costs.n})`,r.costs.net,3)],[],['Date','First-session return','Gross P/L','Fees + tax','Execution','Net P/L']];
 r.costs.rows.forEach((x,i)=>{const row=14+i,dailyIndex=r.daily.findIndex(d=>d.ticker===r.config.tickers[0]&&d.date===x.date)+2;fees.push([D(x.date),F(`Daily!H${dailyIndex}`,x.gross/f.notional),F(`$B$2*B${row}`,x.gross,3),F(`((MAX($B$2*$B$3/100,$B$4)+$B$2*$B$5/100+$B$6)+(MAX(($B$2+C${row})*$B$3/100,$B$4)+($B$2+C${row})*$B$5/100+$B$6))*(1+$B$7/100)`,x.fees,3),F(`(2*$B$2+C${row})*$B$8/10000`,x.execution,3),F(`C${row}-D${row}-E${row}`,x.net,3)]);});
 add('Fees',fees,[40,24,22,22,22,22],false,1);
 add('Data quality',[['Ticker','Input bars','Invalid bars','Off-session bars','Incomplete days','Current/future days','Complete days','Matched days','Excluded dates'],...r.diagnostics.map(x=>[x.ticker,x.inputBars,x.invalidBars,x.outsideSession,x.incompleteDays,x.currentOrFutureDays,x.completeDays,x.matchedDays,x.excludedDays.join(', ')])]);
 add('Daily',dailyRows);add('Raw',rawRows,[18,18,20,18,18,18,18,20]);
 add('Method',[['Setting / source','Value'],['Engine version',VERSION],['Data source',r.source],['Retrieved',r.retrievedAt],['Generated',r.createdAt],['Price basis','Price returns, dividends excluded; no automatic total-return adjustment.'],['Config JSON',JSON.stringify(r.config)],['Sources','https://www.sgx.com/securities/trading ; https://www.nyse.com/markets/hours-calendars'],...r.warnings.map((x,i)=>[`Method / limit ${i+1}`,x])],[27,130],false);
 const main='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
 const files={'[Content_Types].xml':`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`,
 '_rels/.rels':`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
 'xl/workbook.xml':`<workbook xmlns="${main}" xmlns:r="${rel}"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`,
 'xl/_rels/workbook.xml.rels':`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="${rel}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="${rel}/styles" Target="styles.xml"/></Relationships>`,
 'xl/styles.xml':`<styleSheet xmlns="${main}"><numFmts count="3"><numFmt numFmtId="164" formatCode="0.000%"/><numFmt numFmtId="165" formatCode="#,##0.00"/><numFmt numFmtId="166" formatCode="yyyy-mm-dd"/></numFmts><fonts count="2"><font><sz val="11"/><color rgb="FF142039"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF182B4C"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE8EFFF"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="166" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="165" fontId="0" fillId="3" borderId="0" xfId="0" applyNumberFormat="1" applyFill="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`};
 sheets.forEach((s,i)=>{files[`xl/worksheets/sheet${i+1}.xml`]=s.xml;});
 const chartNS='http://schemas.openxmlformats.org/drawingml/2006/chart',drawNS='http://schemas.openxmlformats.org/drawingml/2006/main',sheetDrawNS='http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing';
 files['[Content_Types].xml']=files['[Content_Types].xml'].replace('</Types>','<Override PartName="/xl/charts/chart1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawingml.chart+xml"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/></Types>');
 files['xl/worksheets/sheet1.xml']=files['xl/worksheets/sheet1.xml'].replace('<worksheet xmlns=',`<worksheet xmlns:r="${rel}" xmlns=`).replace('</worksheet>','<drawing r:id="rId1"/></worksheet>');
 files['xl/worksheets/_rels/sheet1.xml.rels']=`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${rel}/drawing" Target="../drawings/drawing1.xml"/></Relationships>`;
 files['xl/drawings/_rels/drawing1.xml.rels']=`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${rel}/chart" Target="../charts/chart1.xml"/></Relationships>`;
 files['xl/drawings/drawing1.xml']=`<xdr:wsDr xmlns:xdr="${sheetDrawNS}" xmlns:a="${drawNS}"><xdr:twoCellAnchor><xdr:from><xdr:col>0</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>19</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:to><xdr:col>8</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>38</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="2" name="Hourly average returns"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm><a:graphic><a:graphicData uri="${chartNS}"><c:chart xmlns:c="${chartNS}" xmlns:r="${rel}" r:id="rId1"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor></xdr:wsDr>`;
 const colors=['315EE8','159589','9C6CCA','DB903E','CF5974','64748B'];
 const series=r.tickers.map((t,i)=>{const rows=r.hourly.filter(x=>x.ticker===t),start=2+i*7;return `<c:ser><c:idx val="${i}"/><c:order val="${i}"/><c:tx><c:v>${xml(t)}</c:v></c:tx><c:spPr><a:solidFill><a:srgbClr val="${colors[i]}"/></a:solidFill></c:spPr><c:cat><c:strRef><c:f>Hourly!$B$${start}:$B$${start+6}</c:f><c:strCache><c:ptCount val="7"/>${rows.map((x,j)=>`<c:pt idx="${j}"><c:v>${xml(x.interval)}</c:v></c:pt>`).join('')}</c:strCache></c:strRef></c:cat><c:val><c:numRef><c:f>Hourly!$E$${start}:$E$${start+6}</c:f><c:numCache><c:formatCode>0.000%</c:formatCode><c:ptCount val="7"/>${rows.map((x,j)=>`<c:pt idx="${j}"><c:v>${x.mean}</c:v></c:pt>`).join('')}</c:numCache></c:numRef></c:val></c:ser>`;}).join('');
 files['xl/charts/chart1.xml']=`<c:chartSpace xmlns:c="${chartNS}" xmlns:a="${drawNS}" xmlns:r="${rel}"><c:chart><c:autoTitleDeleted val="1"/><c:plotArea><c:layout/><c:barChart><c:barDir val="col"/><c:grouping val="clustered"/><c:varyColors val="0"/>${series}<c:gapWidth val="110"/><c:axId val="10"/><c:axId val="20"/></c:barChart><c:catAx><c:axId val="10"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="b"/><c:tickLblPos val="nextTo"/><c:crossAx val="20"/><c:crosses val="autoZero"/></c:catAx><c:valAx><c:axId val="20"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="l"/><c:majorGridlines/><c:numFmt formatCode="0.00%" sourceLinked="0"/><c:tickLblPos val="nextTo"/><c:crossAx val="10"/><c:crosses val="autoZero"/><c:crossBetween val="between"/></c:valAx></c:plotArea><c:legend><c:legendPos val="b"/><c:layout/></c:legend><c:plotVisOnly val="1"/></c:chart></c:chartSpace>`;
 return zip(files);
}
